/**
 * @module polar_codec_wasm
 * @description TypeScript wrapper for the Polar Codec WebAssembly implementation.
 *
 * This module provides a high-level, memory-safe API for encoding and decoding
 * data using Polar Codes -- a class of error-correcting codes that achieve the
 * capacity of symmetric binary-input discrete memoryless channels.
 *
 * The underlying codec is written in Rust and compiled to WebAssembly via wasm-pack.
 * The Wasm binary is embedded as Base64 at bundle time, so no external file
 * loading is required at runtime.  The module works in Node.js, browsers, and Deno.
 *
 * @example
 * ```ts
 * import { PolarCodec } from 'polar_codec_wasm';
 *
 * const codec = new PolarCodec(8, 16);          // K=8 information bits, N=16 total bits
 * const data  = new Uint8Array([1,0,1,1,0,0,1,0]);
 * const encoded = codec.encode_bit(data);       // -> Uint8Array of length N
 * ```
 */

// ---------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------

// Raw glue code generated by wasm-pack.  esbuild inlines its contents during bundling.
import {
  Algorithm,
  Codec,
  Crc,
  FrozenBits,
  initSync,
  type InitOutput,
} from "../pkg/polar_codec_wasm.js";

// Base64-encoded Wasm binary, generated by the build script.
import { WASM_BASE64 } from "./wasm-b64.js";

export { Crc };

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

/** Whether the Wasm module has already been instantiated. */
let isReady = false;

/** Cached reference to the initialized Wasm module. */
let wasm: InitOutput;

/**
 * Decode the Base64-encoded Wasm binary into a `Uint8Array`.
 *
 * The function is cross-environment:
 * - Node.js: uses the native `Buffer` class for fast decoding.
 * - Browser / Deno: falls back to `atob`.
 */
function getWasmBytes(): Uint8Array {
  if (typeof Buffer !== "undefined") {
    // Node.js environment: high-speed decoding
    return Buffer.from(WASM_BASE64, "base64");
  } else {
    // Browser / Deno environments: native `atob` decoding
    const str = atob(WASM_BASE64);
    const wasmBytes = new Uint8Array(str.length);
    for (let i = 0; i < str.length; i++) {
      wasmBytes[i] = str.charCodeAt(i);
    }
    return wasmBytes;
  }
}


// ---------------------------------------------------------------------------
// Public helpers
// ---------------------------------------------------------------------------

/**
 * Synchronously initialize the WebAssembly environment.
 *
 * This function is idempotent -- it is safe to call multiple times; subsequent
 * calls will return the cached module immediately.
 *
 * @returns The initialized Wasm module ready for use.
 *
 * @example
 * ```ts
 * import { initWasmSync } from 'polar_codec_wasm';
 * initWasmSync();
 * // Now PolarCodec can be instantiated.
 * ```
 */
export function initWasmSync(): InitOutput {
  if (isReady) return wasm!;

  const wasmBytes = getWasmBytes();
  // Feed the byte stream to the `initSync` function provided by wasm-bindgen.
  const _wasm = initSync({ module: wasmBytes });
  isReady = true;
  wasm = _wasm;
  return wasm!;
}


// ---------------------------------------------------------------------------
// Type definitions
// ---------------------------------------------------------------------------

/**
 * Description of a user-defined CRC algorithm.
 *
 * Fields follow the [Catalogue of parametrised CRC algorithms](https://reveng.sourceforge.io/crc-catalogue/all.htm).
 */
export interface DefinedCrc {
  /** Optional human-readable name (e.g. `"CRC-16/USB"`). */
  name?: string;
  /** Polynomial degree in bits (e.g. 16 for CRC-16). */
  width: number;
  /** Generator polynomial (without the leading x^width term). */
  poly: number | bigint;
  /** Initial value of the CRC register. */
  init: number | bigint;
  /** Reflect input bytes before processing?  Defaults to `refout` if omitted. */
  refin?: boolean;
  /** Reflect the register before final XOR?  Defaults to `refin` if omitted. */
  refout?: boolean;
  /** XOR mask applied after processing all bytes. */
  xorout?: number | bigint;
}

/**
 * Frozen-bits selection method.
 *
 * | Value | Description |
 * |-------|-------------|
 * | `"5G"` | 5G NR (default for N <= 1024) |
 * | `"RM"` | Reed-Muller (default for N > 1024) |
 * | `"GA"` | Gaussian Approximation with configurable sigma |
 */
export type FrozenBitsMethod =
  | "5G"
  | "RM"
  | { type: "5G" | "RM" }
  | { type: "GA"; sigma?: number };

/**
 * Configuration options accepted by {@link PolarCodec}.
 */
export interface PolarCodecOptions {
  /** Frozen-bits construction method. */
  frozenBits?: FrozenBitsMethod;
  /** CRC scheme -- pass `null` / `undefined` for no CRC, a `Crc` enum value, or a {@link DefinedCrc} object. */
  crc?: Crc | DefinedCrc | null;
}

export function bits_to_llr(bits: Uint8Array): Float32Array {
  const llr = new Float32Array(bits.length);
  for (let i = 0; i < bits.length; i++) {
    llr[i] = bits[i] === 0 ? 10.0 : -10.0; // LLR for BPSK: 0 -> +10, 1 -> -10
  }
  return llr;
}


// ---------------------------------------------------------------------------
// PolarCodec
// ---------------------------------------------------------------------------

/**
 * High-level wrapper around the Rust-backed {@link Codec}.
 *
 * `PolarCodec` manages Wasm initialization and provides a convenient
 * constructor that translates human-readable option names into the
 * low-level enum values expected by the Wasm layer.
 *
 * @typeParam K - Number of information bits (set at construction time).
 * @typeParam N - Codeword length (must be a power of two, >= K).
 *
 * @example
 * ```ts
 * // 5G-style frozen bits, no CRC, list-size L=4 (default)
 * const codec = new PolarCodec(96, 128);
 *
 * // With CRC-16 and GA frozen bits
 * const codec2 = new PolarCodec(96, 128, 4, {
 *   frozenBits: { type: "GA", sigma: 0.5 },
 *   crc: Crc.CRC_16_UMTS,
 * });
 * ```
 */
export class PolarCodec extends Codec {
  /** Number of information bits per codeword. */
  public readonly K: number;

  /** Total codeword length (information + frozen bits). */
  public readonly N: number;

  /** SCL list size used during decoding. */
  public readonly L: number;

  /** Frozen-bits construction method name. */
  public readonly METHOD: "5G" | "RM" | "GA";

  /** Resolved CRC parameters, or `undefined` when no CRC is used. */
  public readonly CRC: Required<DefinedCrc> | undefined;

  /**
   * Create a new Polar Codec instance.
   *
   * @param k  Number of information bits (must be <= n).
   * @param n  Codeword length, must be a power of two.
   * @param l  SCL list size (default `4`).  Larger values improve error
   *           correction at the cost of higher latency and memory.
   * @param options  Optional CRC and frozen-bits configuration.
   */
  constructor(k: number, n?: number, l: number = 4, options: Partial<PolarCodecOptions> = {}) {
    // Ensure the Wasm module is loaded before calling into Rust.
    initWasmSync();

    n ??= 1 << Math.ceil(Math.log2(k));
    let fb: FrozenBits;
    let sigma: number | null = null;
    let crc: Crc | null = null;
    let user_crc: Algorithm | null = null;
    let _crc: Required<DefinedCrc> | undefined = undefined;

    // ======================== Frozen Bits ========================
    // Determine which frozen-bits construction method to use.
    // Accepts a shorthand string or a detailed object form.
    if (typeof options.frozenBits === "string") {
      if (options.frozenBits === "5G") {
        fb = FrozenBits._5G;
      } else if (options.frozenBits === "RM") {
        fb = FrozenBits.RM;
      } else {
        throw new Error(`Invalid frozenBits string: ${options.frozenBits}`);
      }
    } else if (typeof options.frozenBits === "object" && options.frozenBits !== null) {
      if (options.frozenBits.type === "5G" || options.frozenBits.type === "RM") {
        fb = FrozenBits._5G;
      } else if (options.frozenBits.type === "GA") {
        fb = FrozenBits.GA;
        sigma = options.frozenBits.sigma ?? null;
      } else {
        throw new Error(`Invalid frozenBits object type: ${(options.frozenBits as any).type}`);
      }
    } else if (options.frozenBits === undefined) {
      // Auto-select: 5G for short blocks, RM for long blocks.
      fb = n <= 1024 ? FrozenBits._5G : FrozenBits.RM;
    } else {
      throw new Error(`Invalid frozenBits type: ${typeof options.frozenBits}`);
    }

    // ======================== CRC ========================
    // Determine CRC configuration.
    if (typeof options.crc === "number") {
      crc = options.crc;
      if (crc === Crc.UserDefined) {
        throw new Error("Use DefinedCrc object instead of the vague Crc.UserDefined id");
      }
    } else if (options.crc === undefined || options.crc === null) {
      crc = Crc.None;
    } else if (typeof options.crc === "object" && options.crc !== null) {
      // Build a custom CRC Algorithm from the user-supplied fields.
      const width = options.crc.width;
      const poly = BigInt(options.crc.poly);
      const init = options.crc.init !== undefined
        ? BigInt(options.crc.init)
        : ((1n << BigInt(width)) - 1n);          // default: all ones
      const refin = options.crc.refin ?? options.crc.refout ?? true;
      const refout = options.crc.refout ?? refin;
      const xorout = options.crc.xorout !== undefined
        ? BigInt(options.crc.xorout)
        : ((1n << BigInt(width)) - 1n);          // default: all ones

      user_crc = new Algorithm(width, poly, init, refin, refout, xorout);
      crc = Crc.UserDefined;
      _crc = { name: options.crc.name ?? "", width, poly, init, refin, refout, xorout };
    } else {
      throw new Error(`Invalid Crc type: ${typeof options.crc}`);
    }

    // Initialize the Rust-backed Codec through wasm-bindgen.
    super(k, n, l, crc, fb, user_crc, sigma);

    this.K = k;
    this.N = n;
    this.L = l;
    this.METHOD = fb === FrozenBits.GA ? "GA" : fb === FrozenBits.RM ? "RM" : "5G";
    this.CRC = _crc;
  }

  static bits_to_llr(bits: Uint8Array): Float32Array {
    return bits_to_llr(bits);
  }
}