// Import the raw glue code generated by wasm-pack (esbuild will inline its contents during bundling)
import {
  Algorithm,
  Codec,
  Crc,
  FrozenBits,
  initSync,
  type InitOutput,
} from "../pkg/polar_codec_wasm.js";
import { WASM_BASE64 } from "./wasm-b64.js";


let isReady = false;
let wasm: InitOutput; // Will hold the initialized Wasm module once ready

function getWasmBytes(): Uint8Array {
  // Cross-environment Base64 decoding logic
  if (typeof Buffer !== "undefined") {
    // Node.js environment: High-speed decoding
    return Buffer.from(WASM_BASE64, "base64");
  } else {
    // Browser / Deno environments: Native `atob` decoding
    const str = atob(WASM_BASE64);
    const wasmBytes = new Uint8Array(str.length);
    for (let i = 0; i < str.length; i++) {
      wasmBytes[i] = str.charCodeAt(i);
    }
    return wasmBytes;
  }
}

/**
 * Initializes the WebAssembly environment.
 * * It is safe to call this multiple times; subsequent calls will immediately return
 * if the environment is already initialized.
 * 
 * @returns {InitOutput} Returns the initialized Wasm module when it is ready to use.
 * @example
 * import { initWasmSync } from 'polar_codec_wasm';
 * initWasmSync();
 * const codec = new PolarCodec(384, 512, 8);
 */
export function initWasmSync(): InitOutput {
  if (isReady) return wasm!;

  let wasmBytes: Uint8Array = getWasmBytes();
  // Feed the byte stream to the `init` function provided by wasm-bindgen
  const _wasm = initSync({ module: wasmBytes });
  isReady = true;
  wasm = _wasm;
  return wasm!;
}


export interface DefinedCrc {
  name?: string;
  width: number;
  poly: number | bigint;
  init: number | bigint;
  refin?: boolean;
  refout?: boolean;
  xorout?: number | bigint;
}

export type FrozenBitsMethod = "5G" | "RM" | { type: "5G" | "RM" } | { type: "GA", sigma: number };

export interface PolarCodecOptions {
  frozenBits: FrozenBitsMethod;
  crc: Crc | DefinedCrc | null;
}

export class PolarCodec extends Codec {
  public readonly K: number;
  public readonly N: number;
  public readonly L: number;
  public readonly METHOD: "5G" | "RM" | "GA";
  public readonly CRC: Required<DefinedCrc> | undefined;

  constructor(k: number, n: number, l: number = 4, options: Partial<PolarCodecOptions> = {}) {
    initWasmSync();
    let fb: FrozenBits;
    let sigma: number | null = null;
    let crc: Crc | null = null;
    let user_crc: Algorithm | null = null;
    let _crc: Required<DefinedCrc> | undefined = undefined;

    // ===========  Frozen Bits  ===============
    if (typeof options.frozenBits === "string") {
      if (options.frozenBits === "5G") {
        fb = FrozenBits._5G;
      } else if (options.frozenBits === "RM") {
        fb = FrozenBits.RM;
      } else {
        throw new Error(`Invalid frozenBits string: ${options.frozenBits}`);
      }
    } else if (typeof options.frozenBits === "object") {
      if (options.frozenBits.type === "5G" || options.frozenBits.type === "RM") {
        fb = FrozenBits._5G;
      } else if (options.frozenBits.type === "GA") {
        fb = FrozenBits.GA;
        sigma = options.frozenBits.sigma ?? null;
      } else {
        throw new Error(`Invalid frozenBits object type: ${options.frozenBits.type}`);
      }
    } else if (options.frozenBits === undefined) {
      fb = n <= 1024 ? FrozenBits._5G : FrozenBits.RM;
    } else {
      throw new Error(`Invalid frozenBits type: ${typeof options.frozenBits}`);
    }

    // ===========  Crc  ===============
    if (typeof options.crc === "number") {
      crc = options.crc;
      if (crc === Crc.UserDefined) throw new Error("Use Defined Crc instead of vague crc id");
    } else if (options.crc === undefined || options.crc === null) {
      crc = Crc.None
    } else if (typeof options.crc === "object" && options.crc !== null) {
      const width = options.crc.width;
      const poly = BigInt(options.crc.poly);
      const init = options.crc.init !== undefined ? BigInt(options.crc.init) : ((1n << BigInt(width)) - 1n);
      const refin = options.crc.refin ?? options.crc.refout ?? true;
      const refout = options.crc.refout ?? refin;
      const xorout = options.crc.xorout !== undefined ? BigInt(options.crc.xorout) : ((1n << BigInt(width)) - 1n);
      user_crc = new Algorithm(width, poly, init, refin, refout, xorout);
      crc = Crc.UserDefined;
      _crc = { name: options.crc.name ?? "", width, poly, init, refin, refout, xorout };
    } else {
      throw new Error(`Invalid Crc type: ${typeof options.crc}`);
    }
    super(k, n, l, crc, fb, user_crc, sigma);

    this.K = k;
    this.N = n;
    this.L = l;
    switch (fb) {
      case FrozenBits._5G: this.METHOD = "5G"; break;
      case FrozenBits.GA: this.METHOD = "5G"; break;
      case FrozenBits.RM: this.METHOD = "5G"; break;
    }
    this.CRC = _crc;
  }
}